### PR TITLE
got mac working... need to figure out why input isn't working however

### PR DESCRIPTION
**Pull request by MrManiacc**
It's rendering fine with the library I built on my mac, but input isn't working. This is a step in the right direction though.

### CODE REVIEW

**Comment by MrManiacc** [comment]
Never mind on the input not working, it's working fine. You just need to set the imgui size to the framebuffer size instead of window size on mac, and you also need to multiply the io.setMousePos x/y by the width and height scale of the framebuffer. The bindings I posted are working flawlessly, feel free to upload them to the maven repo.

**Comment by SpaiR** [comment]
Hi!

Thanks for you contribution. I realy glad someone is ready to go through macos pitfalls, before me. That will simplify the process in future for sure. Yet before doing of the official release I'll need to make an infrustructure to be able to do releases by myself

In the near future I believe I'll get an access to MacOS. Then I'll use a build configuration made by you. Until then, I would ask to provide more info about the problems you've met while building the library. It will help a lot.

**Comment by MrManiacc** [comment]
I think the main issue was in the GenerateLibs groovy task file, I had to create a new BuildTarget, and manually install the libraries if they weren't already present. Turns out most things get installed on mac under ``/usr/local/include``. That gave me issuses because I thought it would be similar to the unix file system and be located under the X11 folder. But after finding the locations, there was another problem that the default mac target had the command ``-mmacosx-version-min=10.5``, which doesn't allow you to use the correct ``-stdlib=libc++`` command. This is because the libc++ lib requires mac 10.7+, so you have to replace the main command with``mac.cppFlags.replaceAll("10.5", "10.10")``. This allows us to compile using the correct libraries and it will build the dylib.

**Comment by MrManiacc** [comment]
for now, i've include a working dylib file for others to test inside my [fork](https://github.com/MrManiacc/imgui-java). It's also important to note, inside the [ImGui class](https://github.com/MrManiacc/imgui-java/blob/master/imgui-binding/src/main/java/imgui/ImGui.java), I've updated the resolveFullLibName method to the following: 
```
private static String resolveFullLibName() {
        final boolean isWin = System.getProperty("os.name").toLowerCase().contains("win");
        final boolean isMac = System.getProperty("os.name").toLowerCase().contains("mac");
        final String libPrefix;
        final String libSuffix;

        if (isWin) {
            libPrefix = "";
            libSuffix = ".dll";
        } else if(isMac){
            libPrefix = "";
            libSuffix = ".dylib";
        }else{
            libPrefix = "lib";
            libSuffix = ".so";
        }

        return System.getProperty(LIB_NAME_PROP, libPrefix + LIB_NAME_DEFAULT + libSuffix);
    }
```

**Comment by SpaiR** [comment]
I've finally managed to release a MacOS binding. Your advice's were very helpful. Thanks!

**Pull request closed without merging**
