### PR TITLE
Automatic Module Names

### PR DESCRIPTION
**Pull request by tlf30**
Hello,
This PR adds support for Automatic Module Names added by the Java Module System.

This PR was specifically designed after the conversation from #91.
1. Java 8 is still supported.
2. Most packages did not get renamed
3. Project folder structure remains the same

The modules are as follows (and now listed in the readme):
| Package            | Module        |
|--------------------|---------------|
| imgui-java-app     | imgui.app     |
| imgui-java-binding | imgui.binding |
| imgui-java-lwjgl3  | imgui.lwjgl3  |
| imgui-java-natives | imgui.natives |

~~**Significant breaking change**
The packages `imgui.glfw` and `imgui.gl3` have been renamed to `imgui.lwjgl3.glfw` and `imgui.lwjgl3.gl3`
This will break any applications using `ImGuiImplGlfw` and `ImGuiImplGl3`.
Unfortunately, this is a required change as no two modules can have the same classpath.~~

Please review and let me know what you think.
Thank you,
Trevor

Pinning @SpaiR and @Frooastside 

EDIT: As a bonus, I slipped in that if no signing key is defined that signing will be disabled. This allows for publishing to the local maven repo.

### CODE REVIEW

**Comment by tlf30** [comment]
I may have a work around to prevent the renaming of the above mentioned package. I will play with it and report what I find.

**Comment by tlf30** [comment]
OK, I have finally convinced myself that the new package change to keep backwards compatibility is in compliance with java module system. This should be good to go and keep backwards compatibility.

**Comment by Frooastside** [comment]
With backwards compatibility continuing, this pr should be ready for merge, right?

**Comment by tlf30** [comment]
Yes, i believe it is ready. If someone would like to test is please do so. It worked on my test project.

**Comment by SpaiR** [comment]
LGTM! Looks like a great compromise.

**Pull request merged**
