### PR TITLE
feat(api) update imnodes to latest version

### PR DESCRIPTION
**Pull request by serivesmejia**
## Type of change

- [x] New feature (non-breaking change which adds functionality)

I only pulled the latest version of imnodes from Git. I'm not too familiar when it comes to adding the bindings themselves. Lmk if i need to do anything else

### CODE REVIEW

**Comment by SpaiR** [comment]
For this kind of change, simply updating the submodule version is not enough. The bindings also need to be regenerated, after first adapting them to the changes in the API. You need to open the diff between the versions and review the changes in the files, particularly `imnodes.h`. After adapting the binding, you can generate it using the `generateApi` method. Until then your PR updates nothing.

**Comment by serivesmejia** [comment]
Just to make sure, the generator uses the comments in the Java binding files as the JNI source code right?
image

Also, these getNode____SpacePos did break sometime in 1.87.x ... They are supposed to give back ImVec2, but now that I will get my hands on the binding i guess i could also fix it along the way

image

**Comment by SpaiR** [comment]
> Just to make sure, the generator uses the comments in the Java binding files as the JNI source code right?

Exactly. Comments in this form on native methods are transformed into JNI code with all the necessary wrappers—no additional JNI writing is required.

However, you should ensure you're working with the code inside the `imgui-binding/src/main/java` folder. After that, you need to run the `:imgui-binding:generateApi` command to generate the binding code, which should then be committed. Additionally, when updating submodules, you should run the `generateAst` command as well.

> They are supposed to give back ImVec2, but now that I will get my hands on the binding i guess i could also fix it along the way

Yeah, I see. Change return type to `ImVec2` for those methods. On their example you can also see how `@BindingMethod` annotation works. (It's even simplified API to generate bindings.)

**Comment by serivesmejia** [comment]
i messed this up; i'll create a new repo and make the pr once i have it right

**Pull request closed without merging**
