### PR TITLE
Memory editor extension

### PR DESCRIPTION
**Pull request by tlf30**
This is a set of bindings for the extension: https://github.com/ocornut/imgui_club.
Requested in #109 

Please let me know what you think. I would like some feedback on the naming. The repo that contains this extension is ImGui Club, but the actual extension is MemoryEditor. At one point club contained more than just this extension, but those gradually went elsewhere (I think into the main imgui repo). Because of this I made the classpath `.club`. Please let me know if you would like anything renamed and I will do so. 

Please let me know if you have any other feedback as well. 

@FlorianMichael please comment if this implementation will work for you. See the example app for how to use. 

Thanks,
Trevor

image

### CODE REVIEW

**Comment by FlorianMichael** [comment]
image
The Implementation is always crashing if i click on the combo box in the example

**Comment by SpaiR** [comment]
> image The Implementation is always crashing if i click on the combo box in the example

Because you need to compile binaries for it. To test things locally go to the CI artifacts and put them to the `bin` folder. https://github.com/SpaiR/imgui-java/actions/runs/1759323591

**Comment by FlorianMichael** [comment]
thanks

**Comment by SpaiR** [comment]
@tlf30 Great job!

Speaking about the naming. I would probably prefer something like `memedit` or else instead of just a `club`. It doesn't seem like `imgui_club` will have any additional stuff. Highly likely at some point it will be renamed. So it's better to have more meaningful name from the start.

**Comment by FlorianMichael** [comment]
I mean you could also call the package club.memoryeditor

**Comment by tlf30** [comment]
@SpaiR how does that look? Anything else you want changed?

**Comment by SpaiR** [comment]
@tlf30 I assume you want to change `.h`/`.cpp` files too. 😅

**Comment by tlf30** [comment]
I had forgot the header, sorry I was so focused on the classpath 🤦 
Do you also want the submodule renamed, or kept as the default repo name?

**Comment by SpaiR** [comment]
Everything else looks good for me. Good stuff!

**Pull request merged**
