### PR TITLE
added support for linuxarm64 devices

### PR DESCRIPTION
**Pull request by HilbertCurve**
After some debugging (and a lot of twitch livestream watching) I have compiled an ARM-based shared object file and linked it to both the source code and gradle build files.

### CODE REVIEW

**Comment by SpaiR** [comment]
This should be a part of the CI pipeline and not compiled manually.

**Comment by HilbertCurve** [comment]
Updated the pipeline

**Comment by HilbertCurve** [comment]
FYI for deploying project with arm64 natives to maven, specify <code>-Darch=aarch64</code> as an argument (this may want to be double-checked).

**Comment by HilbertCurve** [comment]
I don't really know how to test github workflows apart from just committing/pushing them here...

**Comment by SpaiR** [comment]
You can enable gh actions for your fork and control the way they run though.

**Comment by HilbertCurve** [comment]
Ok, I'll try it

**Comment by HilbertCurve** [comment]
You may want to turn of your notifications; this debugging process is slow

**Comment by HilbertCurve** [comment]
After many attempts, I can't seem to implement native ARM or AArch compiling via github automation (I don't think they can run things with an arm processor, I've tried everything I can think of.) If you'd like to try, please do.

**Pull request closed without merging**
