### PR TITLE
Added callback binding for InputText

### PR DESCRIPTION
**Pull request by moheng233**
#73

### CODE REVIEW

**Comment by SpaiR** [comment]
@moheng233 Good first PR!
Can I ask you to remove the latest commit (the one with `[ci skip]`). Github can't run checks for it.

**Comment by moheng233** [comment]
Yes, I have deleted it now.

**Comment by SpaiR** [comment]
I see you have some troubles. Keep PR opened, I'll fix them by myself 😉

**Comment by SpaiR** [comment]
I've merged PR with some commits from my side. In general, everything looks good. Thank you!

**Comment by moheng233** [comment]
Thank you so much。

**Pull request merged**
