### PR TITLE
M1 natives support

### PR DESCRIPTION
**Pull request by Tom-Ski**
- Upgrades gdx-jnigen to latest release version.
- Changes the library loader to check for 64bit and arm to pick the right native path.
- Added the new binary. Let me know if you want that removed, or generated yourself/GHA.

Tested this with local maven publishing, GHA untested.

### CODE REVIEW

**Comment by SpaiR** [comment]
Hi! Thank you for your contribution. Changes look solid. Yet there is a problem that GitHub actions infrastructure doesn't support ARM builds of any kind. So for now I can't accept changes like yours. Release pipeline is fully automated and should stay like that. Manual release with compiling of binaries on a local machine is a total routine which I want to avoid.

**Comment by Tom-Ski** [comment]
@SpaiR it is possible to build m1 on mac. My latest changes should add the fixes for these issues in previous builds.

**Comment by SpaiR** [comment]
https://github.com/SpaiR/imgui-java/runs/5160749091?check_suite_focus=true#step:9:2409
Here is the output of the compiling job from your PR. It is said pretty straightforward that it's unsupported. 😕 

You're probably confusing two different things: ability to create configs for ARM builds and ability to actually build them. The first one depends on a generation library (that is what gdx-jnigen can do). The second one depends on a build machine. Unfortunately, I don't know any magical way to create ARM builds on an AMD arch.

**Comment by Tom-Ski** [comment]
https://github.com/Tom-Ski/imgui-java/runs/5161042680?check_suite_focus=true

**Comment by SpaiR** [comment]
I see. Well, then there is a magical way... 😅 Next time please point links to workarounds like that at the first place. That will help to avoid any confusion from the beginning. 
You still need to fix a freetype build though. 😏

**Comment by Tom-Ski** [comment]
I'll reopen this when freetype is compiling and linking correctly to avoid the emails/notifications.

**Pull request closed without merging**
